name: Replace placeholders
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  end-to-end-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Replace
      uses: sufyanadam/replace-placeholders@v3
      with:
        placeholders: |
          {
            "reponame": "${{ github.event.repository.name }}",
            "repoowner": "${{github.actor}}"
          }
        filename-pattern: '*.*'
        search-directory: '*'
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply changes
